export const FETCH_AUTH = "FETCH_AUTH";

export const LOAD_YOUTUBE_VIDEO_DETAILS = "app/LOAD_YOUTUBE_VIDEO_DETAILS";
export const LOAD_YOUTUBE_VIDEO_DETAILS_SUCCESS =
	"app/LOAD_YOUTUBE_VIDEO_DETAILS_SUCCESS";
export const CLEAR_LOADED_VIDEO = "app/CLEAR_LOADED_VIDEO";

// Player
export const UPDATE_STATUS = "app/UPDATE_ACTION";
export const UPDATE_TIME = "app/UPDATE_TIME";
export const UPDATE_PLAYER_VIDEO_ID = "app/UPDATE_PLAYER_VIDEO_ID";
export const RESET_VIDEO = "app/RESET_VIDEO";
export const SEEK_TO_TIME = "app/SEEK_TO_TIME";
