export const FETCH_AUTH = "FETCH_AUTH";

export const LOAD_YOUTUBE_VIDEO_DETAILS = "app/LOAD_YOUTUBE_VIDEO_DETAILS";
export const LOAD_YOUTUBE_VIDEO_DETAILS_SUCCESS =
	"app/LOAD_YOUTUBE_VIDEO_DETAILS_SUCCESS";
export const CLEAR_LOADED_VIDEO = "app/CLEAR_LOADED_VIDEO";
